### ISSUE TITLE
Page Rendering

### ISSUE THREAD

**Issue by sdhunt** [DMatedi/prj-rev-bwfs-tea-cozy#1]
Good work implementing a web page that captures the essence of the project specification.

The fixed header works well, with main content scrolling underneath it.

Although the specification called for solid black for the "Our Mission" bar over the image, I do like your design choice to go for 80% opacity - it gives the page an elegant look. 

A couple of issues: 
(1) The spec called for font-family "Helvetica", but in my browser it rendered _Times New Roman_ (the default). 
Looking in your CSS, I see you defined `trebuchet`, but that did not work when I viewed it.

(2) The navigation links in the header should be `seashell`, but they are the default blue / purple (`a`, `a:visited`). 
 
(3) The navigation links should adjust the content so that the appropriate section is moved to the top of the view port.
* This can be fixed by adding "id" names to the href fragments, and adding the respective ids to the appropriate elements. 
https://github.com/DMatedi/prj-rev-bwfs-tea-cozy/blob/93bfeb1662244802db3010b81fe08982abe61c22/teaCozy/index.html#L14-L18

For example:
```
<nav> 
  <span><a href="#mission">Mission</a></span> 
  <span><a href="#featured-tea">Featured Tea</a></span> 
  <span><a href="#locations">Locations</a></span> 
</nav> 
```
and...
```
      <div id="mission" class="first">
      ...

      <div id="featured-tea" class="second">
      ...

      <div id="locations" class="location">
      ...
```

**Comment by DMatedi** [comment]
Thanks for the feedback. Accept my apologies for not replying your comments before or make the Dasmoto exercises you recommended. This is the first online course I'm participating and still getting used to it. 
I really like Trebuchet. What should I do to make sure all visitors see the same thing?
I tried some code but no success.
Thanks,
