### ISSUE TITLE
Do not use <br/> for vertical spacing

### ISSUE THREAD

**Issue by sdhunt** [DMatedi/prj-rev-bwfs-tea-cozy#4]
https://github.com/DMatedi/prj-rev-bwfs-tea-cozy/blob/93bfeb1662244802db3010b81fe08982abe61c22/teaCozy/index.html#L85-L90

Do not use `<br/>` for vertical spacing. Instead, wrap the text pieces in their own elements, and use CSS to control the spacing.

For example:
```
<div class="address"> 

  <div class="donwtown"> 
    <h3>Downtown</h3> 
    <p>384 West 4th St</p>
    <p>Suite 108</p>
    <p>Portland, Maine</p> 
  </div> 
```
in the CSS:
```
.address p {
    ...
}
```

**Comment by DMatedi** [comment]
I changed _br_ to _p  /p_  but since I saw no difference in the design's elements, I choose not to alter _p_ of __css_ .address._
