### ISSUE TITLE
Unnecessary duplication in CSS

### ISSUE THREAD

**Issue by sdhunt** [DMatedi/prj-rev-bwfs-tea-cozy#5]
https://github.com/DMatedi/prj-rev-bwfs-tea-cozy/blob/93bfeb1662244802db3010b81fe08982abe61c22/teaCozy/resources/css/style.css#L140-L156

CSS classes are designed specifically for applying common styles to recurring elements in the document. For example:
```
.addr { 
  background-color: black; 
  height: 230px; 
  width: 300px; 
 } 

.addr p {
  margin: 4px;
}
```
and in the HTML
```
    <div class="address">
      <div class="addr">
        <h3>Downtown</h3>
        <p> ... </p>
        <p> ... </p>
        <p> ... </p>
      </div>

      <div class="addr">
        <h3>East Bayside</h3>
        <p> ... </p>
        <p> ... </p>
        <p> ... </p>
      </div>

      <div class="addr">
        <h3>Oakdale</h3>
        <p> ... </p>
        <p> ... </p>
        <p> ... </p>
      </div>
    </div>
```

**Comment by DMatedi** [comment]
I know I should have done that, but for some reason, I wasn't able to make it work. The background disappears every time I tried to alter it...
