### ISSUE TITLE
SUMMARY: Meets Expectations

### ISSUE THREAD

**Issue by sdhunt** [DMatedi/prj-rev-bwfs-tea-cozy#6]
_Grade:_ __Meets Expectations__

Over all, not a bad implementation of the Tea Cozy project. Your use of comments and whitespace in the source code is good, breaking up the code into readable chunks. You have a pretty good idea on the indentation required. 

Some things to pay attention to:
* Add navigation with anchor fragments and element ids
* Don't use inline styles - define styles in the CSS stylesheet
* Don't use `<br/>` elements for vertical spacing; define that in the CSS
* Avoid duplication of CSS rules, when a CSS class can capture the common style

Some further reading: 
* https://learn.shayhowe.com/html-css/writing-your-best-code/
* https://css-tricks.com/the-difference-between-id-and-class/

Carry on coding.

**Comment by DMatedi** [comment]
Thank you, it has been a difficult week since the last exercise. I'll more than one lesson a day just to keep up with the course time. 
Still excited about this course...  :)

**Comment by DMatedi** [comment]
If I may, I'd like to suggest putting the _target:_"blank"_ at the links. Codecademy does, but GitHub doesn't use the target attribute regularly. 
I'm aware of the shortcut command+right-click, but it would be easier if...
